# *Setup*

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%%time
import numpy as np
import pandas as pd

from hid_avan.eda import head_tail_info
from hid_avan.preprocessing import build_timeseries_df_from_daily_pr_dataset
from hid_avan.Thiessen import thiessen

CPU times: total: 1.83 s
Wall time: 47 s

# EDA

## Visualização tabular geral dos *datasets* brutos

In [3]:
df = pd.read_csv('../data/raw/34750000.txt', header=None)
head_tail_info(df=df, n=3)

<class 'pandas.DataFrame'>
RangeIndex: 8090 entries, 0 to 8089
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8090 non-null   float64
 1   1       8090 non-null   float64
dtypes: float64(2)
memory usage: 126.5 KB

              0         1
0    -40.814582 -4.626249
1    -40.813749 -4.626249
2    -40.813749 -4.627083
8087 -40.813749 -4.624583
8088 -40.814582 -4.624583
8089 -40.814582 -4.626249

None

In [5]:
df = pd.read_excel('../data/raw/34750000_Vazoes.xlsx', parse_dates=['Data'])
head_tail_info(df=df, n=3)

<class 'pandas.DataFrame'>
RangeIndex: 694 entries, 0 to 693
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Data    694 non-null    datetime64[us]
 1   Media   691 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 11.0 KB

          Data     Media
0   1964-02-01       NaN
1   1964-03-01  279.9676
2   1964-04-01  502.0310
691 2021-10-01    0.0000
692 2021-11-01    4.4730
693 2021-12-01    1.3916

None

In [6]:
help(build_timeseries_df_from_daily_pr_dataset)

Help on function build_timeseries_df_from_daily_pr_dataset in module hid_avan.preprocessing.funceme_raw_dataset:

build_timeseries_df_from_daily_pr_dataset(funceme_txt_path: str, date_start: str, date_end: str, missing_pr_value: float | None = -999.0) -> pandas.DataFrame
    Monta um dataframe de séries temporais a partir de um dataset de precipitações diárias da FUNCEME, estando em seu formato bruto,
    opcionalmente substituindo valores faltantes escritos como códigos numéricos (como -999) para NaN.

    Args:
        funceme_txt_path (str): Caminho do dataset bruto em .txt;
        data_start (str): Data do dia inicial no formato 'AAAA-MM-DD';
        data_end (str): Data do dia final no formato 'AAAA-MM-DD';
        missing_pr_value (float or None, optional): Valor numérico correspondente às precipitações faltantes. Se "None", não substitui.

    Returns:
        pd.DataFrame: Séries temporais dispostas nas colunas, identificadas pelo ID da estação, com a coluna 0 constando as datas.

In [7]:
df = build_timeseries_df_from_daily_pr_dataset(funceme_txt_path='../data/raw/pr_daily_funceme_34750000_19730101_20260731.txt',
                                               date_start='1973-01-01', date_end='2026-07-31', missing_pr_value=-999.)
head_tail_info(df=df, n=5)

<class 'pandas.DataFrame'>
RangeIndex: 19570 entries, 0 to 19569
Data columns (total 70 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    19570 non-null  datetime64[us]
 1   2173    2 non-null      float64
 2   36366   1274 non-null   float64
 3   2174    3054 non-null   float64
 4   24012   17449 non-null  float64
 5   24019   19198 non-null  float64
 6   24030   19002 non-null  float64
 7   24037   19174 non-null  float64
 8   24078   19177 non-null  float64
 9   24095   16811 non-null  float64
 10  24150   8062 non-null   float64
 11  24151   6827 non-null   float64
 12  24165   6426 non-null   float64
 13  24167   9397 non-null   float64
 14  24169   6240 non-null   float64
 15  24187   10055 non-null  float64
 16  24190   9518 non-null   float64
 17  24206   3087 non-null   float64
 18  24233   115 non-null    float64
 19  24235   2 non-null      float64
 20  24265   969 non-null    float64
 21  24313   13646 non-null  float64
 22  24315   13768 non-null  float64
 23  24330   11492 non-null  float64
 24  24455   13350 non-null  float64
 25  24456   10510 non-null  float64
 26  24505   13340 non-null  float64
 27  24506   1595 non-null   float64
 28  24510   5197 non-null   float64
 29  24511   11784 non-null  float64
 30  24512   8921 non-null   float64
 31  24552   7179 non-null   float64
 32  24553   5985 non-null   float64
 33  24554   6380 non-null   float64
 34  24555   2657 non-null   float64
 35  24556   1122 non-null   float64
 36  24557   7423 non-null   float64
 37  24558   9243 non-null   float64
 38  24559   7179 non-null   float64
 39  24578   7345 non-null   float64
 40  24579   6713 non-null   float64
 41  24580   5660 non-null   float64
 42  24581   8812 non-null   float64
 43  24582   9124 non-null   float64
 44  24585   8635 non-null   float64
 45  24586   4417 non-null   float64
 46  24587   3160 non-null   float64
 47  24588   7921 non-null   float64
 48  24589   4257 non-null   float64
 49  24590   7341 non-null   float64
 50  24591   5480 non-null   float64
 51  24592   8091 non-null   float64
 52  24598   4390 non-null   float64
 53  24601   4981 non-null   float64
 54  24620   9052 non-null   float64
 55  24629   5467 non-null   float64
 56  24633   3968 non-null   float64
 57  24648   2607 non-null   float64
 58  24651   3501 non-null   float64
 59  24724   1134 non-null   float64
 60  24740   3343 non-null   float64
 61  36620   1011 non-null   float64
 62  36625   1139 non-null   float64
 63  36629   526 non-null    float64
 64  36649   912 non-null    float64
 65  36658   349 non-null    float64
 66  61      4659 non-null   float64
 67  70      3810 non-null   float64
 68  146     12302 non-null  float64
 69  532     5539 non-null   float64
dtypes: datetime64[us](1), float64(69)
memory usage: 10.5 MB

,date,2173,36366,2174,24012,24019,24030,24037,24078,24095,...,24740,36620,36625,36629,36649,36658,61,70,146,532
0,1973-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1973-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
2,1973-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,1973-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
4,1973-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,NaN
19565,2026-07-27,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN
19566,2026-07-28,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN
19567,2026-07-29,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN
19568,2026-07-30,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,...,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN
19569,2026-07-31,NaN,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,...,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN

None

In [9]:
df = build_timeseries_df_from_daily_pr_dataset(funceme_txt_path='../data/raw/pr_daily_funceme_bacia_fronteiras_wgs84_19730101_20260731.txt',
                                               date_start='1973-01-01', date_end='2026-07-31', missing_pr_value=-999.)
head_tail_info(df=df, n=5)

<class 'pandas.DataFrame'>
RangeIndex: 19570 entries, 0 to 19569
Data columns (total 52 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    19570 non-null  datetime64[us]
 1   2173    2 non-null      float64
 2   24019   19198 non-null  float64
 3   24037   19174 non-null  float64
 4   24078   19177 non-null  float64
 5   24150   8062 non-null   float64
 6   24151   6827 non-null   float64
 7   24165   6426 non-null   float64
 8   24167   9397 non-null   float64
 9   24169   6240 non-null   float64
 10  24187   10055 non-null  float64
 11  24190   9518 non-null   float64
 12  24206   3087 non-null   float64
 13  24233   115 non-null    float64
 14  24265   969 non-null    float64
 15  24313   13646 non-null  float64
 16  24315   13768 non-null  float64
 17  24456   10510 non-null  float64
 18  24505   13340 non-null  float64
 19  24512   8921 non-null   float64
 20  24552   7179 non-null   float64
 21  24553   5985 non-null   float64
 22  24554   6380 non-null   float64
 23  24555   2657 non-null   float64
 24  24556   1122 non-null   float64
 25  24557   7423 non-null   float64
 26  24558   9243 non-null   float64
 27  24559   7179 non-null   float64
 28  24586   4417 non-null   float64
 29  24587   3160 non-null   float64
 30  24588   7921 non-null   float64
 31  24589   4257 non-null   float64
 32  24590   7341 non-null   float64
 33  24591   5480 non-null   float64
 34  24592   8091 non-null   float64
 35  24598   4390 non-null   float64
 36  24601   4981 non-null   float64
 37  24620   9052 non-null   float64
 38  24629   5467 non-null   float64
 39  24633   3968 non-null   float64
 40  24648   2607 non-null   float64
 41  24651   3501 non-null   float64
 42  24724   1134 non-null   float64
 43  24740   3343 non-null   float64
 44  36625   1139 non-null   float64
 45  36629   526 non-null    float64
 46  36649   912 non-null    float64
 47  36658   349 non-null    float64
 48  61      4659 non-null   float64
 49  70      3810 non-null   float64
 50  146     12302 non-null  float64
 51  532     5539 non-null   float64
dtypes: datetime64[us](1), float64(51)
memory usage: 7.8 MB

,date,2173,24019,24037,24078,24150,24151,24165,24167,24169,...,24724,24740,36625,36629,36649,36658,61,70,146,532
0,1973-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1973-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
2,1973-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,1973-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
4,1973-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,NaN
19565,2026-07-27,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN
19566,2026-07-28,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN
19567,2026-07-29,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN
19568,2026-07-30,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN
19569,2026-07-31,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN

None

# 2

In [10]:
help(thiessen)

Help on function thiessen in module hid_avan.Thiessen:

thiessen(dados, lat: numpy.ndarray, lon: numpy.ndarray, pathshp: str, pf: float = -1, sep: str = ',', usenc: bool = False, min_est: int = 5, **kwargs)
    Verifica a quantidade de postos dentro de uma região e calcula a média
    de uma variável ponderada pela zona de influência de cada posto.

    Exemplos de postos: Plataformas de Coleta de Dados (PCDs), Postos
                        Pluviométricos, grados em grades regulares, etc.

    Exemplos de regiões: bacias, estados, macro regiões do Ceará, etc.

    Exemplos de variáveis: precipitação, temperatura, etc.

    Os postos também podem ser interpretados como pontos de uma grade regular
    oriundos de modelos numéricos ou dados observados em grade. Muitas vezes, ao
    usar dados em grade, a maioria dos pontos da grade possuem a mesma
    influência dentro da região. Isso vai estar relacionado com tamanho da
    região e a quantidade de pontos em grade encontrados dentro da região.

    Relação entre pf, pf_max, min_est, pf_step:

    O paramentro 'pf' (pontos fora) é usado quando existe a necessidade de
    usar postos fora da região. Geralmente, isso acontece quando a região é
    muito pequena e não encontramos postos dentro da região. O 'pf' indica o
    início da zona (buffer) de procura  de postos fora da região. Na prática,
    um "retângulo" (na maioria das vezes) é usado para determinar a zona de
    procura. 'pf_max' indica o limite máximo do crecismento da zona de procura.
    'pf_step' indica o passo em que a zona de procura vai crescer.

    Exemplos:
        pf=1., pf_max=3., pf_step=0.5 :: A zona de procura iniciará 1 grau
        a partir dos limiares da região até 3 graus. Esse crescimento se dará
        a cada 0.5 graus.
        pf=0., pf_max=5., pf_step=1. :: A zona de procura iniciará 0 grau
        a partir dos limiares da região até 5 graus. Esse crescimento se dará
        a cada 1 grau.

    NOTA: 1 grau é aproximadamente 110km nas regiões próximo ao equardor.

    O min_est (mínimo de postos ou estações) indica o número mínimo de postos
    que, se encontrados durante o crescimento da zona de procura,
    irão interromper a procura de postos fora da região. É usado para
    determinar o número mínimo de postos que representa a região.

    Exemplos:
        pf=0., pf_max=5., pf_step=1., min_est=3 :: O crescimento da zona de
        procura será interrompido se o algoritimo encontrar 2 (dois) postos.

    :param dados:    - Matriz 3d com os dados que serão calculados as médias de thiessen. Formato dado[time, lat, lon]
    :param lat:      - Numpy array com as latitudes do arquivo nc
    :param lon:      - Numpy array com as longitudes do arquivo nc.
                       [obs: longitudes serão alteradas para o range de -180 a 180]
    :param pathshp:  - String com o caminho do shape do poligono. (ex: arquivo.dat)
    :param pf:       - Valor em graus para inserir pontos próximos que estão fora da bacia ( -1 não inclui ).
                       (ex: pf = 1, busca pontos fora a partir de 1 grau))
    :param sep:      - Separador do arquivo de pontos do shape. Delimitador default " , "
    :param usenc:    - Dados do tipo netcdf [True, False].
    :param figname:  - Opcional   Nome da figura (ex: thiessen.png)
    :param num_proc: - numero de processadores
    :return thimed:  - média de thiessen para a variável de entrada
    :return thimed, thimax, thimin, numpostos:  - média, max, min de thiessen para a variável de entrada e num de postos